# ===========================================================================
#   Script from the hdf5-manylinux repo: 
#     https://github.com/h5py/hdf5-manylinux/blob/master/Dockerfile_aarch64
# ===========================================================================

FROM quay.io/pypa/manylinux2014_aarch64

ENV HDF5_DIR /usr/local
ENV HDF5_VERSION 1.12.1

COPY install_libaec.sh /tmp/install_libaec.sh
RUN bash /tmp/install_libaec.sh
COPY install_hdf5_centos.sh /tmp/install_hdf5.sh
RUN bash /tmp/install_hdf5.sh

