FROM quay.io/pypa/manylinux_2_24_x86_64

ENV HDF5_DIR /usr/local
ENV HDF5_VERSION 1.12.1

COPY install_libaec.sh /tmp/install_libaec.sh
RUN bash /tmp/install_libaec.sh
COPY install_hdf5_debian.sh /tmp/install_hdf5.sh
RUN bash /tmp/install_hdf5.sh

